/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mimt_honeypot;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static mimt_honeypot.Browse.filepath;

/**
 *
 * @author EGC
 */
public class Preprocess extends javax.swing.JFrame {

    /**
     * Creates new form Preprocess
     */
    Vector columnNames =new Vector();
    Vector data=new Vector();
    Vector columnNames1 = new Vector();
    Vector data2 = new Vector();
    DefaultTableModel model,model1;
     String x_time,x_source,x_destination,x_protocol,x_length,x_info,x_s_no,x_target;
     public  int counter=0;
    public Preprocess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 130, 334, 376));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Preprocess");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 183, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 310, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 526));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Preprocessing");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loaddata.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 470, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/honeypot_mimt", "root", "");
            Statement stmt = con.createStatement();
            //Statement stmt1 = con.createStatement();

            System.out.println(" DataBase Connected");
           stmt.executeUpdate("TRUNCATE TABLE preprocess");

            try{
         
//             stmt.executeUpdate("INSERT into preprocess SELECT * FROM data ");
//             
//            
//
//                //JOptionPane.showMessageDialog(null,"There is no null value in the dataset");
//
//                //stmt.executeUpdate("UPDATE preprocess set pregnancies=0,glucose=0  WHERE pregnancies = 'NULL' || glucose='NULL' ");
                
            //System.out.println("hi");
           filepath="./Dataset/packets.csv";
            FileInputStream fi=new FileInputStream(filepath);
//           File fi1=new File(filepath);
//           System.out.println(fi1.getName());
            //System.out.println(fn);
            DataInputStream di=new DataInputStream(fi);
            BufferedReader br=new BufferedReader(new InputStreamReader(di));
            String read=br.readLine();
            while((read=br.readLine())!=null)
            {
                String line=read;
                String r[]=line.split(",");
                int a=line.split(",").length;
                String state = "";
               //counter=0;
                 for(int i=0;i<a;i++){
                     for(int j=0;j<a;j++){
                 if(r[j].contains(",")){
                         r[i]=r[i].replace(",",""); 
                 }
                 }
                     }   
                 for(int i=0;i<a;i++){
                     
                    if(r[i].isEmpty()){
                        r[i]="0";
                         counter++;
                      
                        System.out.println("count"+counter); 
                           
                    }
                    
                                     
                    
                    System.out.println(r[i]);
                    
                    } 
                 System.out.println("counter1"+counter);
                 int x=0;
                x_s_no=r[x];
                x_time=r[x+1];
                x_source=(r[x+2]);
                x_destination=r[x+3];
                x_protocol=(r[x+4]);
                x_length=r[x+5];
                x_info=(r[x+6]);
                 x_target=(r[x+7]);              

                /*  if(isArrayEmpty(r)){
                    System.out.println(r[x]+"divya");
                }*/

                //stmt.executeUpdate("TRUNCATE TABLE preprocess");

                
                stmt.executeUpdate("INSERT INTO preprocess VALUES('"+x_s_no+"','"+ x_time+"','"+x_source+"','"+x_destination+"','"+x_protocol
                        +"','"+x_length+"','"+x_info+"','"+x_target+"')");
            }
            System.out.println("counter"+counter);
             if(counter==0){
                JOptionPane.showMessageDialog(this," Missing Values: "+counter);
            }
                 else{
                   JOptionPane.showMessageDialog(this,"Missing Values: "+counter);  
                 }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e+"KK");
                e.printStackTrace();
            }
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");

                Statement stmt1 = con.createStatement();

                ResultSet rs1 = stmt1.executeQuery("SELECT * from preprocess");
                ResultSetMetaData rsmd = rs1.getMetaData();
                int columns = rsmd.getColumnCount();

                for(int i=1;i<=columns;i++)
                {
                    columnNames.addElement(rsmd.getColumnName(i));
                }
                while(rs1.next())
                {
                    // data.na.fill(0);
                    /* if (entry.getValue() == "")
                    entry.setValue(defaultValue); */
                    Vector row=new Vector(columns);
                    for(int i=1;i<=columns;i++)
                    {
                        System.out.println(rs1.getObject(i));
                        row.addElement(rs1.getObject(i));

                    }
                    /*  for(int i=1;i<=columns.length;i++)
                    {
                    }*/
                    data.addElement(row);

                }
                rs1.close();
                model=new DefaultTableModel(data, columnNames);
                jTable1.setModel(model);

                JOptionPane.showMessageDialog(this, "Preprocess Successfully");
            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
                e.printStackTrace();
            }}
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
                e.printStackTrace();
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Split().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preprocess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
